### PR TITLE
Download pybind via CMake

### PR DESCRIPTION
**Pull request by volkm**

### CODE REVIEW

**Comment by sjunges** [comment]
This should be synced with a PR for stormpy as we currently rely on pybind version compatibility (due to the flags that we override).

**Comment by volkm** [comment]
As far as I know there are no custom flags in pybind11 anymore. In my understanding, starting with PR #5 the pybind11 dir is equal to the original one without any custom adaptions.
At least the local test were successful for me with the new pybind version in pycarl and the old one in stormpy.
Nevertheless, we should update stormpy as well.

**Comment by volkm** [comment]
Maybe it might even be an idea to not ship pybind11 in the repo but either download it via cmake or include it as a [Git submodule](https://pybind11.readthedocs.io/en/latest/installing.html#include-as-a-submodule).

**Comment by sjunges** [comment]
Yes, we can now use the pybind direction without changes as we set flags from the outside.
My understanding however is that these flags, in particular, https://github.com/moves-rwth/stormpy/blob/b0505e893cb277b9a910d3d1276f17f2b9eb8504/CMakeLists.txt#L13 may yield problems if the pybind versions are not compatible, see https://pybind11.readthedocs.io/en/stable/upgrade.html?highlight=different%20versions#stricter-enforcement-of-hidden-symbol-visibility-for-pybind11-modules.

**Comment by sjunges** [comment]
> Maybe it might even be an idea to not ship pybind11 in the repo but either download it via cmake or include it as a [Git submodule](https://pybind11.readthedocs.io/en/latest/installing.html#include-as-a-submodule).

This is a good idea!

**Comment by volkm** [comment]
The visibility seems indeed to require the same pybind version for both libraries. Thanks for reminding me of this issue.

**Comment by volkm** [comment]
My proposal is to add a cmake file for pybind which takes care of downloading a specified version. That way we have full control over the pybind version which is used.

**Comment by volkm** [comment]
The proposed change downloads pybind11 in the configure step such that it is available for `add_subdirectory`.

The functionality requires CMake version 3.14 which is why the tests on Debian 10 were removed. If we want to keep supporting older versions, I could implement the [workaround](https://cliutils.gitlab.io/modern-cmake/chapters/projects/fetch.html) which only requires CMake 3.11.

**Comment by sjunges** [comment]
LGTM

**Comment by volkm** [comment]
The recent changes allow to set the pybind version from CMake and as a setup.py argument. The pybind version is also exported such that stormpy can use it later on. Note that for the shipped version we export the tag used of pybind as the version (and do not explicitly check that the download is indeed the correct version).

**Comment by sjunges** [comment]
I tried real hard but I have not a single comment. Many thanks for building this part, very nice improvement!

**Comment by volkm** [comment]
Thanks for checking. And even more for not finding anything ;)

**Pull request merged**
