### PR TITLE
Implement manually triggered github actions CI

### PR DESCRIPTION
**Pull request by dbasgoeze**
Should need no secrets as secrets.GITHUB_TOKEN is autogenerated.

The workflow is meant to run on every push, that would be

```
on:
  push:
    branches:
      - master
```

### CODE REVIEW

**Comment by nafur** [comment]
It's not that I don't like the storm guys, but could you "rebrand" the CI jobs to use carl or pycarl instead of storm? (using the storm base system is okay... :-) )

**Comment by dbasgoeze** [comment]
> It's not that I don't like the storm guys, but could you "rebrand" the CI jobs to use carl or pycarl instead of storm? (using the storm base system is okay... :-) )

Do you mean the internal name for the docker container?

**Comment by nafur** [comment]
> > It's not that I don't like the storm guys, but could you "rebrand" the CI jobs to use carl or pycarl instead of storm? (using the storm base system is okay... :-) )
> 
> Do you mean the internal name for the docker container?

yes.

**Comment by dbasgoeze** [comment]
Ok, can do. The workflow was just based on the one from stormpy and storm.

**Comment by dbasgoeze** [comment]
Fixed and tested

**Pull request merged**
